# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_application_path
  generated_xcode_build_settings_path = File.expand_path(File.join('..', '.flutter-plugins-dependencies'))
  if File.exist?(generated_xcode_build_settings_path)
    File.foreach(generated_xcode_build_settings_path) do |line|
      matches = line.match(/FLUTTER_APPLICATION_PATH="(.+)"/)
      if matches && matches[1]
        return matches[1]
      end
    end
  end
  return nil
end

def flutter_application_framework_group
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated)
    generated = File.expand_path(File.join('..', '.flutter-plugins-dependencies'))
  end
  unless File.exist?(generated)
    return nil
  end

  app_framework_group = nil
  File.foreach(generated) do |line|
    matches = line.match(/FLUTTER_APPLICATION_FRAMEWORK_GROUP="(.+)"/)
    if matches && matches[1]
      app_framework_group = matches[1]
      break
    end
  end
  app_framework_group
end

# Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
# referring to absolute paths on developers' machines.
system('rm -rf .symlinks')
system('mkdir -p .symlinks/plugins')

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_application_path)

flutter_application_path && install_all_flutter_pods(flutter_application_path)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path && install_all_flutter_pods(flutter_application_path)

  target 'RunnerTests' do
    inherit! :search_paths
  end

  target 'RunnerUITests' do
    # Pods for testing are installed by default if you have tests in your project.
    # You may want to remove this if you don't have tests.
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # This is a workaround for a CocoaPods issue that causes the build to fail
    # when using use_frameworks! with certain Flutter plugins.
    # See: https://github.com/flutter/flutter/issues/42693
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      # Workaround for permission_handler plugin
      if target.name == 'PermissionHandler'
        config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      end
    end
  end
end
